export const adminMenuItems = [
  { id: "dashboard", label: "Quản trị hệ thống", icon: "bi-speedometer2", path: "/admin" },
  { id: "customers", label: "Quản lý tài khoản", icon: "bi-people", path: "/admin/customers" },
  { id: "stationery", label: "Quản lý văn phòng phẩm", icon: "bi-pen", path: "/admin/stationery" },
  { id: "books", label: "Quản lý sách", icon: "bi-book", path: "/admin/books" },
  { id: "toys", label: "Quản lý đồ chơi", icon: "bi-puzzle", path: "/admin/toys" },
  { id: "accessories", label: "Quản lý phụ kiện", icon: "bi-watch", path: "/admin/accessories" },
  { id: "souvenirs", label: "Quản lý quà lưu niệm", icon: "bi-gift", path: "/admin/souvenirs" },
  { id: "school", label: "Quản lý đồ dùng học tập", icon: "bi-backpack", path: "/admin/school" },
  { id: "categories", label: "Quản lý danh mục", icon: "bi-tags", path: "/admin/categories" },
  { id: "inventory", label: "Quản lý tồn kho", icon: "bi-box-seam", path: "/admin/inventory" },
  { id: "authors", label: "Quản lý tác giả", icon: "bi-person-vcard", path: "/admin/authors" },
  { id: "publishers", label: "Quản lý nhà xuất bản", icon: "bi-building", path: "/admin/publishers" },
  { id: "brands", label: "Quản lý thương hiệu", icon: "bi-tag", path: "/admin/brands" },
  { id: "manufacturers", label: "Quản lý nhà sản xuất", icon: "bi-gear", path: "/admin/manufacturers" },
  { id: "promotions", label: "Quản lý khuyến mãi", icon: "bi-megaphone", path: "/admin/promotions" },
  { id: "orders", label: "Quản lý đơn hàng", icon: "bi-cart-check", path: "/admin/orders" },
  { id: "shipping", label: "Quản lý giao hàng", icon: "bi-truck", path: "/admin/shipping" },
  { id: "reviews", label: "Quản lý đánh giá", icon: "bi-chat-left-text", path: "/admin/reviews" },
  { id: "messages", label: "Quản lý tin nhắn", icon: "bi-envelope-paper", path: "/admin/messages" },
  { id: "recruitments", label: "Quản lý tuyển dụng", icon: "bi-person-lines-fill", path: "/admin/recruitments" },
  { id: "reports", label: "Báo cáo thống kê", icon: "bi-graph-up-arrow", path: "/admin/reports" },
];