using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookStore.Api.Migrations
{
    /// <inheritdoc />
    public partial class CreateAdditionalCategoryTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create accessory table only if it doesn't already exist (some environments
            // created these tables manually or via earlier scripts). Using raw SQL here
            // ensures migrations are idempotent across environments.
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c WHERE c.relname = 'AccessoryCategories' AND pg_catalog.pg_table_is_visible(c.oid)) THEN
        CREATE TABLE ""AccessoryCategories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500),
            ""ImageUrl"" character varying(500),
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone,
            CONSTRAINT ""PK_AccessoryCategories"" PRIMARY KEY (""Id"")
        );
    END IF;
END
$$;" );

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c WHERE c.relname = 'SchoolSupplyCategories' AND pg_catalog.pg_table_is_visible(c.oid)) THEN
        CREATE TABLE ""SchoolSupplyCategories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500),
            ""ImageUrl"" character varying(500),
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone,
            CONSTRAINT ""PK_SchoolSupplyCategories"" PRIMARY KEY (""Id"")
        );
    END IF;
END
$$;" );

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c WHERE c.relname = 'SouvenirCategories' AND pg_catalog.pg_table_is_visible(c.oid)) THEN
        CREATE TABLE ""SouvenirCategories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500),
            ""ImageUrl"" character varying(500),
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone,
            CONSTRAINT ""PK_SouvenirCategories"" PRIMARY KEY (""Id"")
        );
    END IF;
END
$$;" );

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c WHERE c.relname = 'StationeryCategories' AND pg_catalog.pg_table_is_visible(c.oid)) THEN
        CREATE TABLE ""StationeryCategories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500),
            ""ImageUrl"" character varying(500),
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone,
            CONSTRAINT ""PK_StationeryCategories"" PRIMARY KEY (""Id"")
        );
    END IF;
END
$$;" );

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class c WHERE c.relname = 'ToyCategories' AND pg_catalog.pg_table_is_visible(c.oid)) THEN
        CREATE TABLE ""ToyCategories"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""Description"" character varying(500),
            ""ImageUrl"" character varying(500),
            ""CreatedAt"" timestamp with time zone NOT NULL,
            ""UpdatedAt"" timestamp with time zone,
            CONSTRAINT ""PK_ToyCategories"" PRIMARY KEY (""Id"")
        );
    END IF;
END
$$;" );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AccessoryCategories");

            migrationBuilder.DropTable(
                name: "SchoolSupplyCategories");

            migrationBuilder.DropTable(
                name: "SouvenirCategories");

            migrationBuilder.DropTable(
                name: "StationeryCategories");

            migrationBuilder.DropTable(
                name: "ToyCategories");
        }
    }
}
